pub const AppEntry = struct {
    label: []const u8,
    command: []const u8,
    monogram: []const u8,
    accent: [3]f64,
    subtitle: []const u8 = "",
    keywords: []const u8 = "",
    shortcut: []const u8 = "",
    enabled: bool = true,
};

pub const entries = [_]AppEntry{
    .{
        .label = "Terminal",
        .command = "exec env SHELL=\"$(command -v fish)\" ghostty --shell-integration=fish",
        .monogram = "T",
        .accent = .{ 0.23, 0.78, 0.72 },
        .subtitle = "Emulador de terminal",
        .keywords = "shell console bash fish terminal ghostty",
        .shortcut = "Ctrl + 1",
    },
    .{
        .label = "Firefox",
        .command = "firefox",
        .monogram = "F",
        .accent = .{ 0.95, 0.48, 0.20 },
        .subtitle = "Navegador web",
        .keywords = "browser navegador internet web firefox",
        .shortcut = "Ctrl + 2",
    },
    .{
        .label = "Arquivos",
        .command = "exec \"$AXIA_BIN_DIR/axia-files\"",
        .monogram = "A",
        .accent = .{ 0.29, 0.66, 0.94 },
        .subtitle = "Explorador de arquivos do Axia-DE",
        .keywords = "files explorer arquivos pastas documentos",
        .shortcut = "Ctrl + 3",
    },
    .{
        .label = "VS Code",
        .command = "code",
        .monogram = "VS",
        .accent = .{ 0.20, 0.55, 0.96 },
        .subtitle = "Editor de código",
        .keywords = "editor code vscode programação desenvolvimento",
        .shortcut = "Ctrl + 4",
    },
    .{
        .label = "Steam",
        .command = "steam",
        .monogram = "S",
        .accent = .{ 0.35, 0.47, 0.66 },
        .subtitle = "Jogos e biblioteca",
        .keywords = "steam jogos games biblioteca",
        .shortcut = "Ctrl + 5",
    },
    .{
        .label = "Rede",
        .command = "exec \"$AXIA_BIN_DIR/axia-settings\" network",
        .monogram = "R",
        .accent = .{ 0.26, 0.72, 0.92 },
        .subtitle = "Configurações de rede do Axia-DE",
        .keywords = "rede wifi ethernet internet conexao conexões dns proxy",
    },
    .{
        .label = "Impressoras",
        .command = "exec \"$AXIA_BIN_DIR/axia-settings\" printers",
        .monogram = "I",
        .accent = .{ 0.68, 0.58, 0.90 },
        .subtitle = "Configurações de impressoras do Axia-DE",
        .keywords = "impressora impressoras printer impressão scanner",
    },
    .{
        .label = "Bluetooth",
        .command = "exec \"$AXIA_BIN_DIR/axia-settings\" bluetooth",
        .monogram = "B",
        .accent = .{ 0.38, 0.69, 0.94 },
        .subtitle = "Configurações de Bluetooth do Axia-DE",
        .keywords = "bluetooth pareamento audio fone dispositivos",
    },
    .{
        .label = "Configurações",
        .command = "exec \"$AXIA_BIN_DIR/axia-settings\"",
        .monogram = "C",
        .accent = .{ 0.54, 0.77, 0.88 },
        .subtitle = "Central de ajustes do Axia-DE",
        .keywords = "configuracoes configuração ajustes rede impressora aparência wallpaper sistema",
    },
};
