pub const AppEntry = struct {
    label: []const u8,
    id: []const u8,
    command: []const u8,
    monogram: []const u8,
    icon: []const u8 = "",
    accent: [3]f64,
    subtitle: []const u8 = "",
    keywords: []const u8 = "",
    shortcut: []const u8 = "",
    enabled: bool = true,
    favorite: bool = false,
};

pub const entries = [_]AppEntry{
    .{
        .label = "Terminal",
        .id = "terminal",
        .command = "if command -v alacritty >/dev/null 2>&1; then exec env SHELL=\"$(command -v fish || command -v sh)\" alacritty --class terminal --title Terminal -o 'window.decorations=\"None\"'; elif command -v foot >/dev/null 2>&1; then exec env SHELL=\"$(command -v fish || command -v sh)\" foot; else exec xterm; fi",
        .monogram = "T",
        .icon = "terminal",
        .accent = .{ 0.23, 0.78, 0.72 },
        .subtitle = "Emulador de terminal",
        .keywords = "shell console bash fish terminal alacritty",
        .shortcut = "Ctrl + 1",
        .favorite = true,
    },
    .{
        .label = "Navegador",
        .id = "default-browser",
        .command = "xdg-open about:blank",
        .monogram = "N",
        .icon = "web-browser",
        .accent = .{ 0.95, 0.48, 0.20 },
        .subtitle = "Navegador padrão do sistema",
        .keywords = "browser navegador internet web default padrão",
        .shortcut = "Ctrl + 2",
        .favorite = true,
    },
    .{
        .label = "Arquivos",
        .id = "axia-files",
        .command = "exec \"$AXIA_BIN_DIR/axia-files\"",
        .monogram = "A",
        .icon = "axia-files",
        .accent = .{ 0.29, 0.66, 0.94 },
        .subtitle = "Explorador de arquivos do Axia-DE",
        .keywords = "files explorer arquivos pastas documentos",
        .shortcut = "Ctrl + 3",
        .favorite = true,
    },
    .{
        .label = "VS Code",
        .id = "code",
        .command = "code",
        .monogram = "VS",
        .icon = "visual-studio-code",
        .accent = .{ 0.20, 0.55, 0.96 },
        .subtitle = "Editor de código",
        .keywords = "editor code vscode programação desenvolvimento",
        .shortcut = "Ctrl + 4",
        .favorite = true,
    },
    .{
        .label = "Steam",
        .id = "steam",
        .command = "steam",
        .monogram = "S",
        .icon = "steam",
        .accent = .{ 0.35, 0.47, 0.66 },
        .subtitle = "Jogos e biblioteca",
        .keywords = "steam jogos games biblioteca",
        .shortcut = "Ctrl + 5",
    },
    .{
        .label = "Rede",
        .id = "axia-settings-network",
        .command = "exec \"$AXIA_BIN_DIR/axia-settings\" network",
        .monogram = "R",
        .icon = "preferences-system-network",
        .accent = .{ 0.26, 0.72, 0.92 },
        .subtitle = "Configurações de rede do Axia-DE",
        .keywords = "rede wifi ethernet internet conexao conexões dns proxy",
    },
    .{
        .label = "Impressoras",
        .id = "axia-settings-printers",
        .command = "exec \"$AXIA_BIN_DIR/axia-settings\" printers",
        .monogram = "I",
        .icon = "printer",
        .accent = .{ 0.68, 0.58, 0.90 },
        .subtitle = "Configurações de impressoras do Axia-DE",
        .keywords = "impressora impressoras printer impressão scanner",
    },
    .{
        .label = "Bluetooth",
        .id = "axia-settings-bluetooth",
        .command = "exec \"$AXIA_BIN_DIR/axia-settings\" bluetooth",
        .monogram = "B",
        .icon = "bluetooth",
        .accent = .{ 0.38, 0.69, 0.94 },
        .subtitle = "Configurações de Bluetooth do Axia-DE",
        .keywords = "bluetooth pareamento audio fone dispositivos",
    },
    .{
        .label = "Configurações",
        .id = "axia-settings",
        .command = "exec \"$AXIA_BIN_DIR/axia-settings\"",
        .monogram = "C",
        .icon = "settings-axia",
        .accent = .{ 0.54, 0.77, 0.88 },
        .subtitle = "Central de ajustes do Axia-DE",
        .keywords = "configuracoes configuração ajustes rede impressora aparência wallpaper sistema",
        .favorite = true,
    },
};
